apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gismap-database-cluster
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  destination:
    name: ''
    namespace: gisdemo
    server: 'https://kubernetes.default.svc'
  source:
    path: kustomize/postgres
    repoURL: 'https://github.com/nfickas/postgis-demo.git'
    targetRevision: HEAD
  project: default